import { contextBridge, ipcRenderer } from 'electron'
import { CMD, EVT } from './ipc.js'
import type { SettingsPatch, TokensPatch, Playbook } from './ipc.js'

function sub(channel: string, cb: (payload: unknown) => void): () => void {
  const listener = (_e: unknown, payload: unknown): void => cb(payload)
  ipcRenderer.on(channel, listener as never)
  return () => ipcRenderer.removeListener(channel, listener as never)
}

contextBridge.exposeInMainWorld('watchpup', {
  activityList: (range = 'recent') => ipcRenderer.invoke(CMD.activityList, range),
  onActivitySessions: (cb: (sessions: unknown) => void) => sub(EVT.activitySessions, cb),
  onActivityFocus: (cb: (id: unknown) => void) => sub('activity.focus', cb),
  openActivity: (id: string) => ipcRenderer.send('activity.open', id),
  openActivityDetail: (id?: string) => ipcRenderer.send('activity.detail', id),
  mentionsList: () => ipcRenderer.invoke(CMD.mentionsList),
  mentionGet: (id: string) => ipcRenderer.invoke(CMD.mentionGet, id),
  mentionRead: (id: string) => ipcRenderer.invoke(CMD.mentionRead, id),
  todoToggle: (id: string, index: number) => ipcRenderer.invoke(CMD.todoToggle, { mentionId: id, index }),
  replyApprove: (id: string) => ipcRenderer.invoke(CMD.replyApprove, id),
  replyCopy: (id: string) => ipcRenderer.invoke(CMD.replyCopy, id),
  replyRewrite: (id: string, style: string) => ipcRenderer.invoke('reply.rewrite', { mentionId: id, style }),
  chatSend: (id: string, text: string) => ipcRenderer.invoke(CMD.chatSend, { mentionId: id, text }),
  settingsGet: () => ipcRenderer.invoke(CMD.settingsGet),
  settingsSet: (patch: SettingsPatch) => ipcRenderer.invoke(CMD.settingsSet, patch),
  tokensGet: () => ipcRenderer.invoke(CMD.tokensGet),
  tokensSet: (patch: TokensPatch) => ipcRenderer.invoke(CMD.tokensSet, patch),
  playbooksList: () => ipcRenderer.invoke(CMD.playbooksList),
  playbookUpsert: (pb: Playbook) => ipcRenderer.invoke(CMD.playbookUpsert, pb),
  playbookDelete: (id: string) => ipcRenderer.invoke(CMD.playbookDelete, id),
  mcpList: () => ipcRenderer.invoke('mcp.list'),
  mcpUpsert: (s: unknown) => ipcRenderer.invoke('mcp.upsert', s),
  mcpRemove: (id: string) => ipcRenderer.invoke('mcp.remove', id),
  mcpImportCandidates: () => ipcRenderer.invoke('mcp.importCandidates'),
  integrationStatus: () => ipcRenderer.invoke('integration.status'),
  connectNotion: (token: string) => ipcRenderer.invoke('integration.connectNotion', token),
  connectJira: (a: { site: string; email: string; token: string }) => ipcRenderer.invoke('integration.connectJira', a),
  disconnectIntegration: (id: string) => ipcRenderer.invoke('integration.disconnect', id),
  actionRun: (mentionId: string, playbookId: string, extra?: string) => ipcRenderer.invoke(CMD.actionRun, { mentionId, playbookId, extra }),
  onPet: (cb: (s: unknown) => void) => sub(EVT.pet, cb),
  onMentionNew: (cb: (m: unknown) => void) => sub(EVT.mentionNew, cb),
  onMentionReady: (cb: (m: unknown) => void) => sub(EVT.mentionReady, cb),
  onChatStream: (cb: (p: unknown) => void) => sub(EVT.chatStream, cb),
  onBadge: (cb: (n: unknown) => void) => sub(EVT.badge, cb),
  onBubble: (cb: (text: unknown) => void) => sub(EVT.bubble, cb),
  onChatBubble: (cb: (ev: unknown) => void) => sub(EVT.chatBubble, cb),
  onPetTheme: (cb: (name: unknown) => void) => sub(EVT.petTheme, cb),
  onPetImages: (cb: (map: unknown) => void) => sub(EVT.petImages, cb),
  onPetSize: (cb: (value: unknown) => void) => sub(EVT.petSize, cb),
  onBubbleSize: (cb: (value: unknown) => void) => sub(EVT.bubbleSize, cb),
  onHudSize: (cb: (value: unknown) => void) => sub(EVT.hudSize, cb),
  onHudAlignment: (cb: (value: unknown) => void) => sub(EVT.hudAlignment, cb),
  onHudVisibility: (cb: (value: unknown) => void) => sub(EVT.hudVisibility, cb),
  petImages: () => ipcRenderer.invoke('pet.images.get'),
  pickPetImageDir: () => ipcRenderer.invoke('pet.pickImageDir'),
  pickObsidianVault: () => ipcRenderer.invoke('obsidian.pickVault'),
  skillPick: () => ipcRenderer.invoke('skill.pick'),
  codexList: () => ipcRenderer.invoke('codex.list'),
  codexPickDir: () => ipcRenderer.invoke('codex.pickDir'),
  codexUse: (dir: string) => ipcRenderer.invoke('codex.use', dir),
  petCodex: () => ipcRenderer.invoke('pet.codex.get'),
  threadGet: (id: string, refresh = false) => ipcRenderer.invoke('thread.get', id, refresh),
  reactionSet: (mentionId: string, messageTs: string, name: string, active: boolean) =>
    ipcRenderer.invoke(CMD.reactionSet, { mentionId, messageTs, name, active }),
  groupsList: () => ipcRenderer.invoke('groups.list'),
  groupsResearch: () => ipcRenderer.invoke('groups.research'),
  groupsRemove: (id: string) => ipcRenderer.invoke('groups.remove', id),
  onMentionsRefresh: (cb: () => void) => sub('mentions.refresh', () => cb()),
  reposList: () => ipcRenderer.invoke('repos.list'),
  reposAdd: () => ipcRenderer.invoke('repos.add'),
  reposAddGithub: (spec: string) => ipcRenderer.invoke('repos.addGithub', spec),
  reposRemove: (path: string) => ipcRenderer.invoke('repos.remove', path),
  devRun: (mentionId: string, repoPaths: string[], extraContext: string) =>
    ipcRenderer.invoke('dev.run', { mentionId, repoPaths, extraContext }),
  sendFeedback: (mentionId: string, text: string) => ipcRenderer.invoke('feedback.send', { mentionId, text }),
  reanalyze: (id: string) => ipcRenderer.invoke('mention.reanalyze', id),
  rate: (mentionId: string, score: number) => ipcRenderer.invoke('mention.rate', { mentionId, score }),
  lessonsList: () => ipcRenderer.invoke('lessons.list'),
  lessonsClear: (key?: string, index?: number) => ipcRenderer.invoke('lessons.clear', { key, index }),
  lessonsAdd: (key: string, text: string) => ipcRenderer.invoke('lessons.add', { key, text }),
  lessonsEdit: (key: string, index: number, text: string) => ipcRenderer.invoke('lessons.edit', { key, index, text }),
  onLessonsChanged: (cb: () => void) => sub('lessons.changed', () => cb()),
  onPetCodex: (cb: (v: unknown) => void) => sub(EVT.petCodex, cb),
  petResize: (size: number | {
    width: number
    height: number
    anchor?: 'left' | 'right'
    verticalAnchor?: 'top' | 'bottom'
  }) => ipcRenderer.send('pet.resize', size),
  onActionStream: (cb: (p: unknown) => void) => sub(EVT.actionStream, cb),
  onActionDone: (cb: (p: unknown) => void) => sub(EVT.actionDone, cb),
  openExternal: (url: string) => ipcRenderer.send('open.external', url),
  hidePanel: () => ipcRenderer.send('panel.hide'),
  minimizePanel: () => ipcRenderer.send('panel.minimize'),
  maximizePanel: () => ipcRenderer.send('panel.maximize'),
  onPanelShown: (cb: () => void) => sub('panel.shown', () => cb()),
  openMention: (id: string) => ipcRenderer.send('pet.openMention', id),
  onMentionFocus: (cb: (id: unknown) => void) => sub('mention.focus', cb),
  setTracked: (mentionId: string, tracked: boolean) => ipcRenderer.invoke('mention.setTracked', { mentionId, tracked }),
  removeMention: (id: string) => ipcRenderer.invoke('mention.remove', id),
  cleanupFalseMentions: () => ipcRenderer.invoke('mention.cleanupFalse'),
  setCategory: (mentionId: string, category: string) => ipcRenderer.invoke('mention.setCategory', { mentionId, category }),
  restartApp: () => ipcRenderer.send('app.restart'),
  showPanel: () => ipcRenderer.send('pet.showPanel'),
  setMouseIgnore: (ignore: boolean) => ipcRenderer.send('pet.setMouseIgnore', ignore),
  petDragStart: () => ipcRenderer.send('pet.dragStart'),
  petDragEnd: () => ipcRenderer.send('pet.dragEnd'),
})
